-- Create Roles
CREATE ROLE IF NOT EXISTS engineer;
CREATE ROLE IF NOT EXISTS analyst;
CREATE ROLE IF NOT EXISTS db_user;

-- Create Wharehouse
CREATE WAREHOUSE IF NOT EXISTS development
WITH
    WAREHOUSE_SIZE = xsmall
    AUTO_SUSPEND = 30
    AUTO_RESUME = true;


-- Create Database
CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;

--Create Schemas
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.raw WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.staging WITH MANAGED ACCESS ;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.marts WITH MANAGED ACCESS ;



-- ACCESS CONTROL

-- engineers: full control of RAW + STAGING
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE engineer;
GRANT ALL ON SCHEMA HEALTHCARE_DB.raw TO ROLE engineer;
GRANT ALL ON SCHEMA HEALTHCARE_DB.staging TO ROLE engineer;


-- analysts: read marts only
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE analyst;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.marts TO ROLE analyst;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_DB.marts TO ROLE analyst;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_DB.marts TO ROLE analyst;

-- db_users: read only access to marts 
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE db_user;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.marts TO ROLE db_user;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_DB.marts TO ROLE db_user;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_DB.marts TO ROLE db_user;