
COPY INTO HEALTHCARE_DB.RAW.HOSPITAL_DATA_RAW
FROM @my_gcs_stage
FILE_FORMAT = (FORMAT_NAME = my_csv_format)

MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT'

INCLUDE_METADATA = (
    ingestion_timestamp = METADATA$START_SCAN_TIME,
    source_file = METADATA$FILENAME
);